version: '2.2'
services:
  section:
    build:
      context: ../..
      dockerfile: Docker/run/Dockerfile
    environment:
      - DB_URL=jdbc:postgresql://sectiondb:5432/section
      - PORT=8080

  sectiondb:
    image: postgres:10.5-alpine
    environment:
      - POSTGRES_USER=section
      - POSTGRES_PASSWORD=section
      - POSTGRES_DB=section
    volumes:
      - service_section_pg_data:/var/lib/postgresql/data

  altair:
    extends:
      file: ../../../../../fanzila/service-section/Docker/test_env/Docker-compose.yml
      service: altair
    environment:
      - SERVER_URL=http://localhost:8080/graphql
      - AUTH_TOKEN=placeTokenHere

volumes:
  service_loyalty_pg_data:
