basePath: /
definitions:
  models.Article:
    properties:
      author:
        $ref: '#/definitions/models.Author'
      categories:
        items:
          $ref: '#/definitions/models.Category'
        type: array
      content:
        type: string
      created_at:
        type: string
      id:
        type: string
      publication_date:
        type: string
      title:
        type: string
      updated_at:
        type: string
    type: object
  models.Author:
    properties:
      created_at:
        type: string
      email:
        type: string
      first_name:
        type: string
      id:
        type: string
      last_name:
        type: string
      updated_at:
        type: string
    type: object
  models.Category:
    properties:
      created_at:
        type: string
      id:
        type: string
      name:
        type: string
      updated_at:
        type: string
    type: object
host: localhost:8000
info:
  contact: {}
  description: API Server for TodoList Application
  title: Todo App API
  version: "1.0"
paths:
  /articles:
    get:
      description: Получение списка всех статей
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Article'
            type: array
      tags:
      - Articles
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
